language: python
python:
     - "2.7.12"
     - "3.5"
     - "3.5"
     - "3.7.0"
     - "nightly"

install: 
    - pip install -r requirements.txt
    - sudo apt-get install pandoc

script:
    - travis-sphinx build
    - py.test test_nb
    - travis-sphinx --source=docs/source
    
after_success:
    - travis-sphinx --branches=master,Lab1 deploy
