language: python
python:
     - "3.5"
     - "3.6"
     - "3.7"
     - "nightly"

install: 
    - pip install -r requirements.txt
    - sudo apt-get install pandoc
    - pip install pytest-django
script:
#    - travis-sphinx build
#   - py.test test_nb.py
    - pytest test_nb.py
#     - travis-sphinx --source=docs/source
    
after_success:
    - travis-sphinx --branches=master,./Lab1 deploy
