language: python
sudo: false

python:
  - "3.5"
  
env:
  - DJANGO=1.10.5

branches:
  only:
     - master

before_install:
  - pip install pytest-cov
  - export DJANGO_SETTINGS_MODULE=frisor.settings
  - export SECRET_KEY='This is secret'
  - export DEBUG=True
  
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
  - source activate test-environment

script:
  - cd Lab1
  - coverage run --source=Lab1.ipynb test
  
  after_success:
  - coverage report
  - coveralls
