language: python
python:
     - "2.7"
     - "2.7"
     - "3.5"
     - "3.6"
     - "3.7"
     - "nightly"
     
before_install:
     - sudo apt-get update
     - sudo apt-get install python-opencv
     - sudo dpkg -L python-opencv

install: 
    - pip install -r requirements.txt
    - sudo apt-get install pandoc
    - pip install pytest-django
    - pip install opencv-python
    
script:
#    - travis-sphinx build
#   - py.test test_nb.py
    - python test_nb.py
#     - travis-sphinx --source=docs/source
  # Download v3.0.0 .zip file and extract.
     - curl -sL https://github.com/Itseez/opencv/archive/3.0.0-beta.zip > opencv.zip
     - unzip opencv.zip
     - cd opencv-3.0.0-beta
     - sudo apt-get update
     - sudo apt-get install libopencv-dev python-opencv
    
after_success:
    - travis-sphinx --branches=master,./Lab1 deploy
