language: python
python:
     - "3.5"
     - "3.6"
     - "3.7"
     - "nightly"

install: 
    - pip install -r requirements.txt
    - sudo apt-get install pandoc
    - pip install pytest-django
script:
#    - travis-sphinx build
#   - py.test test_nb.py
    - pytest test_nb.py
#     - travis-sphinx --source=docs/source
  # Download v3.0.0 .zip file and extract.
     - curl -sL https://github.com/Itseez/opencv/archive/3.0.0-beta.zip > opencv.zip
     - unzip opencv.zip
     - cd opencv-3.0.0-beta
    
after_success:
    - travis-sphinx --branches=master,./Lab1 deploy
