language: python
python:
     - "2.7.12"
     - "3.5"
     - "3.5"
     - "nightly"

install: 
    - pip install -r requirements.txt
    - sudo apt-get install pandoc

script:
    - py.test test_nb
    - travis-sphinx --source Lab1 build

after_success:
    - travis-sphinx --branches=master,Develop deploy
