language: python
python:
     - "2.7"
     - "3.5"
     - "3.6"
     - "nightly"
     
before_install:
     - sudo apt-get update
     - sudo apt-get install python-opencv
     - sudo dpkg -L python-opencv

install: 
    - pip install -r requirements.txt
    - sudo apt-get install pandoc
    - pip install pytest-django
    - pip install opencv-python
    - pip install pytest
script:
#    - travis-sphinx build
#   - py.test test_nb.py
    - pytest test_nb.py
    - python test_nb.py
#      - travis-sphinx build
  # Download v3.0.0 .zip file and extract.
     - curl -sL https://github.com/Itseez/opencv/archive/3.0.0-beta.zip > opencv.zip
     - unzip opencv.zip
     - cd opencv-3.0.0-beta
     - sudo apt-get update
     - sudo apt-get install libopencv-dev python-opencv
after:
    - sudo add-apt-repository python-opencv
    - sudo apt-get update
    - cd ~
 
after_success:
    - travis-sphinx --branches=master,./Project_Prototype deploy
deploy:
  provider: pypi
  user: SunatP
# deploy:
#   provider: releases
#   file_glob: true
#   file: app/build/outputs/Lab/*.ipynb
# skip_cleanup: true
#   on:
#     repo: SunatP/ITCS381_Multimedia
#   api_key:
# secure: 
